stages:

  download_data:
    cmd: python src/data/download_data.py
    params:
      - kaggle_dataset
    outs:
      - data/raw/IMDB Dataset.csv

  train_test_split:
    cmd: python src/features/train_test_split.py
    deps:
      - data/raw/IMDB Dataset.csv
    params:
      - file_path
      - test_size
      - split_seed
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_lstm:
    cmd: python src/models/lstm.py
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - vocab_size
      - embedding_dim
      - max_length
      - trunc_type
      - oov_tok
      - lstm_units
      - num_epochs
    outs:
      - models/lstm/
      - data/fit_history/lstm_history/
